In [1]:
import numpy as np

In [ ]:
## previous sample, use list comprehension
even_list = [i for i in data if i % 2 == 0]
print("even_list: ", even_list)
odd_list = [i for i in data if i % 2 == 1]
print("odd_list: ", odd_list)
triple_list = [i for i in data if i % 3 == 0]
print("triple_list: ", triple_list)

trifive_list = [
    i for i in data 
    if i % 3 == 0 or i % 5 == 0
]
print("trifive_list: ", trifive_list)

## For loop

In [11]:
## for + range

data_dict = {
    "1": "one",
    "2": "two",
    "3": "two",
    "4": "two",
    "5": "two"
}
for index in range(len(data)):
    if str(index) in data_dict:
        print(index, data_dict[str(index)], data[index])
    else:
        print(index, data[index])

0 20
1 one 21
2 two 22
3 two 24
4 two 25
5 two 26
6 29
7 30
8 31
9 35
10 41
11 44
12 45
13 46
14 49


In [9]:
## for + range(A,B,C)
for index in range(2, len(data)-2, 2):
    print(index, data[index])
print("For end")

2 22
4 25
6 29
8 31
10 41
12 45
For end


In [3]:
## for element in series
for i in data:
    print(i)

20
24
25
26
27
28
29
32
33
35
38
39
42
45
48


In [15]:
## enumerate
for index, i in enumerate(data):
    print(index, i)

0 20
1 21
2 22
3 24
4 25
5 26
6 29
7 30
8 31
9 35
10 41
11 44
12 45
13 46
14 49


In [16]:
# re-implement previous sample
even_list = list()
odd_list = list()
tri_list = list()
trifive_list = list()

for i in data:
    if i % 2 == 0:
        even_list.append(i)
    else:
        odd_list.append(i)

    if i % 3 == 0:
        tri_list.append(i)
        trifive_list.append(i)
    elif i % 5 == 0:
        trifive_list.append(i)
        
print(even_list)
print(odd_list)
print(tri_list)
print(trifive_list)

[20, 22, 24, 26, 30, 44, 46]
[21, 25, 29, 31, 35, 41, 45, 49]
[21, 24, 30, 45]
[20, 21, 24, 25, 30, 35, 45]


In [8]:
data

array([58, 82, 41, 39, 68, 59, 65, 99, 89, 20, 30, 65, 53, 37, 43, 54, 61,
       43, 49, 42,  7, 53, 57, 74, 52, 13, 55, 41, 59, 76, 14, 59, 85,  3,
       55, 80, 73, 64, 33, 43, 70, 70, 78, 24, 82, 37, 29, 56, 90, 49, 63,
       39, 92, 24, 75, 56, 41, 98, 28, 69, 53, 85, 87, 23,  1, 59, 88, 98,
       68, 61, 30, 78, 84, 50, 69,  9, 19, 63, 17, 15, 84, 14, 15,  7, 78,
       77, 15, 74, 95, 52, 14, 99, 73, 17,  0, 56, 29, 77, 66, 18])

In [27]:
data[:4]

[20, 21, 22, 24]

In [9]:
## genrate data
data = np.random.randint(20, 50, 20)
data = sorted(set(data))
print(data, len(data))


[22, 23, 28, 29, 31, 33, 34, 35, 38, 42, 45, 47, 48, 49] 14


In [19]:
# nested for loop
filtered_data = list()
sum_list = list()
for idx, element in enumerate(data):
    print("=====================================")
    print("index", idx)
    ## continue
    if idx % 3 == 0:
        print("Index is divided by 3. Continue Loop")
        continue
    
    filtered_data.append(data[idx])
    ##### equivalent to ######################################
    # print(data[:idx+1])
    sub_list = list()
    sum_number = 0
    for sub_element in filtered_data:
        sub_list.append(sub_element)
        sum_number += sub_element
    sum_list.append(sum_number)
    print("sub list:", sub_list)
    ##########################################################
    ## break
    # if sum_number > 280:
    #     break
    print("=====================================")
print("sum_list: ", sum_list)
    

index 0
Index is divided by 3. Continue Loop
index 1
sub list: [23]
quotient list: [0]
index 2
sub list: [23, 28]
quotient list: [1, 0]
index 3
Index is divided by 3. Continue Loop
index 4
sub list: [23, 28, 31]
quotient list: [3, 0, 3]
index 5
sub list: [23, 28, 31, 33]
quotient list: [3, 3, 1, 3]
index 6
Index is divided by 3. Continue Loop
index 7
sub list: [23, 28, 31, 33, 35]
quotient list: [2, 0, 3, 5, 0]
index 8
sub list: [23, 28, 31, 33, 35, 38]
quotient list: [7, 4, 7, 1, 3, 6]
index 9
Index is divided by 3. Continue Loop
index 10
sub list: [23, 28, 31, 33, 35, 38, 45]
quotient list: [3, 8, 1, 3, 5, 8, 5]
index 11
sub list: [23, 28, 31, 33, 35, 38, 45, 47]
quotient list: [1, 6, 9, 0, 2, 5, 1, 3]
index 12
Index is divided by 3. Continue Loop
index 13
sub list: [23, 28, 31, 33, 35, 38, 45, 47, 49]
quotient list: [10, 2, 5, 7, 9, 12, 6, 8, 10]
sum_list:  [23, 51, 82, 115, 150, 188, 233, 280, 329]


## While loop

In [23]:
data = np.random.randint(1, 10, 100)
data

array([7, 9, 5, 4, 6, 3, 9, 5, 8, 4, 2, 4, 6, 4, 9, 6, 7, 2, 9, 7, 5, 9,
       2, 8, 9, 1, 6, 8, 7, 3, 7, 4, 6, 2, 2, 3, 6, 6, 1, 2, 4, 8, 1, 1,
       8, 2, 3, 7, 9, 5, 5, 7, 4, 5, 7, 2, 1, 7, 9, 8, 7, 5, 2, 2, 1, 5,
       6, 5, 7, 7, 5, 3, 9, 5, 6, 7, 2, 7, 4, 4, 2, 8, 6, 2, 1, 6, 4, 1,
       4, 9, 3, 9, 7, 8, 5, 3, 3, 2, 8, 3])

In [24]:
%%time
sum_number = 0
loop_count = 0
while sum_number < 50000000:
    # statement
    sum_number += data[sum_number%100]
    loop_count += 1
    if loop_count > 10000:
        print("Reach loop limit 10000")
        break

print("While loop end.", sum_number)
    

Reach loop limit 10000
While loop end. 57157
CPU times: total: 0 ns
Wall time: 3.99 ms


## Sample

In [26]:
## print triangle
# *
# * *
# * * *
level = range(1, 10)
for i in level:
    print("* "*i)

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 
* * * * * * * * * 


In [41]:
#     *
#   * * *
# * * * * *
level = range(1, 15)
max_level = max(level)

for i in level:
    width = 2*i - 1
    print("  "*(max_level-i), "* "*width ,"  "*(max_level-i))

                           *                            
                         * * *                          
                       * * * * *                        
                     * * * * * * *                      
                   * * * * * * * * *                    
                 * * * * * * * * * * *                  
               * * * * * * * * * * * * *                
             * * * * * * * * * * * * * * *              
           * * * * * * * * * * * * * * * * *            
         * * * * * * * * * * * * * * * * * * *          
       * * * * * * * * * * * * * * * * * * * * *        
     * * * * * * * * * * * * * * * * * * * * * * *      
   * * * * * * * * * * * * * * * * * * * * * * * * *    
 * * * * * * * * * * * * * * * * * * * * * * * * * * *  


In [36]:
#    *
#  * *
#* * *

level = range(1, 10)
max_level = max(level)
for i in level:
    print("  "*(max_level-i), "* "*i)

                 * 
               * * 
             * * * 
           * * * * 
         * * * * * 
       * * * * * * 
     * * * * * * * 
   * * * * * * * * 
 * * * * * * * * * 


In [43]:
## sample : squre list
number_list = np.random.randint(1, 1000, 10)
number_list

array([252, 672, 360, 614, 301, 863, 583, 820, 355, 444])

In [45]:
## Q1, square the element
square_list = list()
for num in number_list:
    square_list.append(num*num)
square_list

[63504, 451584, 129600, 376996, 90601, 744769, 339889, 672400, 126025, 197136]

In [47]:
## Q2, sum the square as element
sum_square = 0
sum_square_list = list()
for num in number_list:
    sum_square += num*num
    sum_square_list.append(sum_square)
sum_square_list

[63504,
 515088,
 644688,
 1021684,
 1112285,
 1857054,
 2196943,
 2869343,
 2995368,
 3192504]

In [48]:
sum(square_list)

3192504